### PR TITLE
Add support to patchesJson6902 in customPatches

### PR DESCRIPTION
**Pull request by alessiodionisi**
SSIA

### CODE REVIEW

**Comment by ralgozino** [comment]
Notice that patchesJson6902 has been deprecated in kustomize v5:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/

The same functionality should be achievable via `patches` that we already support.

**Comment by alessiodionisi** [comment]
Yeah I know, but we use kustomize 3.10.0 :D

**Comment by ralgozino** [comment]
it is already supported by kustomize v3.10.0:

```
❯ cat deployment.yaml kustomization.yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - name: http
              containerPort: 80
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomization.yaml
resources:
- deployment.yaml
patches:
  - patch: |-
      - op: add
        path: /metadata/labels/app.kubernetes.io~1version
        value: 1.21.0
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:1.21.0
    target:
      labelSelector: "app.kubernetes.io/name=nginx"
❯ kustomize version
{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T00:00:50Z GoOs:darwin GoArch:amd64}
❯ kustomize build
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.21.0
  name: dummy-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - image: nginx:1.21.0
        name: nginx
        ports:
        - containerPort: 80
          name: http

```

I would not add the patchesJson6902 option being that we already have a way to do them and knowing that we'll need to deprecate it later, but I'm open to changing my mind :-)

Is there some specific case that does not work with 3.10.0 for example?

**Comment by alessiodionisi** [comment]
@ralgozino tested now and it's working. Thanks for the review, I'll close this PR.

**Pull request closed without merging**
