### PR TITLE
fix: custom registry onpremises configuration

### PR DESCRIPTION
**Pull request by alessiodionisi**
- Added `.spec.kubernetes.advanced` field check

### CODE REVIEW

**Review by stefanoghinelli — APPROVED** [review]
lgtm

**Review by ralgozino — APPROVED** [review]
an improvement that we could do is to set the default value of `.spec.kubernetes.advanced` to `{}` and we can get rid of a lot of if clauses in this file

**Comment by alessiodionisi** [comment]
@ralgozino if I remember correctly we can set defaults only for distribution values with the current template system implementation

**Comment by ralgozino** [comment]
> @ralgozino if I remember correctly we can set defaults only for distribution values with the current template system implementation

I'm not sure I understand. What I ment was that , if we set `.spec.kubernetes.advanced` to an empty object `{}` in the `defaults/onpremises-kfd-v1alpha2.yaml` file like we do for `customPatches` for example, we don't need to check if it is defined in the template.

**Comment by alessiodionisi** [comment]
> > @ralgozino if I remember correctly we can set defaults only for distribution values with the current template system implementation
> 
> I'm not sure I understand. What I ment was that , if we set `.spec.kubernetes.advanced` to an empty object `{}` in the `defaults/onpremises-kfd-v1alpha2.yaml` file like we do for `customPatches` for example, we don't need to check if it is defined in the template.

Unfortunately defaults files are applied only to `spec.distribution` furyctl configurations.

**Pull request merged**
