### PR TITLE
Add type field to ResourceGenerator, remove code duplication

### PR DESCRIPTION
**Pull request by alessiodionisi**
- Make `type` field to `ResourceGenerator` working, used to set Secret type
- Removed code duplication
- Autoformat after Go code generation

### CODE REVIEW

**Review by nutellinoit — DISMISSED** [review]
LGTM!

**Comment by nutellinoit** [comment]
@alessiodionisi do you know why the e2e on the schemas is failing? Maybe the change of the included schema for the plugins?

**Comment by alessiodionisi** [comment]
I've disabled `009 - no` test by commenting it, we need to re-enable it when the JSON schema library supports `unevaluatedProperties`.

**Review by Al-Pragliola — APPROVED** [review]
LGTM

**Pull request merged**
